# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular CI

on:
    push:
        branches: [main, Angular11, Angular13, Angular14, release3.x ]
    pull_request:
        branches: [main, Angular11, Angular13, Angular14, release3.x ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 16, 18, 20]

        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
              node-version: ${{ matrix.node-version }}
        - run: npm install
        - run: npm run build
        - run: npm run test
